#!/usr/bin/env sh

echo 'ffc-sfd-landing-page' &&
  curl --silent "https://api.github.com/repos/defra/ffc-sfd-landing-page/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/'

echo 'ffc-sfd-auth' &&
  curl --silent "https://api.github.com/repos/defra/ffc-sfd-auth/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/'

echo 'ffc-sfd-proxy' &&
  curl --silent "https://api.github.com/repos/defra/ffc-sfd-proxy/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/'

echo 'ffc-sfd-ingress' &&
  curl --silent "https://api.github.com/repos/defra/ffc-sfd-ingress/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/'

echo 'ffc-sfd-data' &&
  curl --silent "https://api.github.com/repos/defra/ffc-sfd-data/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/'

echo 'ffc-sfd-permissions' &&
  curl --silent "https://api.github.com/repos/defra/ffc-sfd-permissions/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/'

echo 'ffc-sfd-preferences-api' &&
  curl --silent "https://api.github.com/repos/defra/ffc-sfd-preferences-api/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/'

echo 'ffc-sfd-ahwp-stub' &&
  curl --silent "https://api.github.com/repos/defra/ffc-sfd-ahwp-stub/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/'
