#!/usr/bin/env sh

echo 'ffc-sfd-landing-page' &&
  curl --silent "https://api.github.com/repos/defra/ffc-sfd-landing-page/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/'

echo 'ffc-sfd-auth' &&
  curl --silent "https://api.github.com/repos/defra/ffc-sfd-auth/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/'

echo 'ffc-sfd-business' &&
  curl --silent "https://api.github.com/repos/defra/ffc-sfd-business/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/'

echo 'ffc-sfd-proxy' &&
  curl --silent "https://api.github.com/repos/defra/ffc-sfd-proxy/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/'

echo 'ffc-sfd-ingress' &&
  curl --silent "https://api.github.com/repos/defra/ffc-sfd-ingress/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/'

echo 'ffc-sfd-data' &&
  curl --silent "https://api.github.com/repos/defra/ffc-sfd-data/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/'

echo 'ffc-sfd-permissions' &&
  curl --silent "https://api.github.com/repos/defra/ffc-sfd-permissions/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/'

echo 'ffc-sfd-permissions-api' &&
  curl --silent "https://api.github.com/repos/defra/ffc-sfd-permissions-api/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/'

echo 'ffc-sfd-ahwp-stub' &&
  curl --silent "https://api.github.com/repos/defra/ffc-sfd-ahwp-stub/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/'
  
echo 'ffc-sfd-messages' &&
  curl --silent "https://api.github.com/repos/defra/ffc-sfd-messages/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/'

echo 'ffc-sfd-messages-processor' &&
  curl --silent "https://api.github.com/repos/defra/ffc-sfd-messages-processor/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/'

echo 'ffc-sfd-customer-receiver-messages' &&
  curl --silent "https://api.github.com/repos/defra/ffc-sfd-customer-receiver-messages/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/'

echo 'ffc-sfd-customer-receiver-payments' &&
  curl --silent "https://api.github.com/repos/defra/ffc-sfd-customer-receiver-payments/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/'

