#!/usr/bin/env sh
set -e
projectRoot="$(a="/$0"; a=${a%/*}; a=${a:-.}; a=${a#/}/; cd "$a/.." || return; pwd)"

show_help() {
  echo "
    Usage: path/to/ffc-sfd-core [OPTION...]
    Open services in VS Code.

    Options:
      -h, --help       display this help text
    "
}

while :; do
  case $1 in
    -h|--help)   # Call a "show_help" function to display a synopsis, then exit.
      show_help
      exit
      ;;
    *)
      break
  esac

  shift
done

cd "${projectRoot}"

code ./ffc-sfd-landing-page;
code ./ffc-sfd-auth;
code ./ffc-sfd-business;
code ./ffc-sfd-data;
code ./ffc-sfd-permissions;
code ./ffc-sfd-permissions-api;
code ./ffc-sfd-ahwp-stub;
code ./ffc-sfd-proxy;
code ./ffc-sfd-ingress;
code ./ffc-sfd-messages;
code ./ffc-sfd-messages-processor;
code ./ffc-sfd-customer-receiver-messages;
code ./ffc-sfd-customer-receiver-payments;
code ./ffc-sfd-customer-receiver-preferences;
code ./ffc-sfd-customer-receiver-queries;
code ./ffc-sfd-queries;