#!/usr/bin/env sh
set -e
projectRoot="$(a="/$0"; a=${a%/*}; a=${a:-.}; a=${a#/}/; cd "$a/.." || return; pwd)"

show_help() {
  echo "
    Usage: path/to/ffc-sfd-core [OPTION...]
    Run git pull in services.

    Options:
      -h, --help       display this help text
    "
}

while :; do
  case $1 in
    -h|--help)   # Call a "show_help" function to display a synopsis, then exit.
      show_help
      exit
      ;;
    *)
      break
  esac

  shift
done

cd "${projectRoot}"
cd ./ffc-sfd-landing-page && \
  git pull
cd "${projectRoot}"
cd ./ffc-sfd-auth && \
  git pull
cd "${projectRoot}"
cd ./ffc-sfd-business && \
  git pull
cd "${projectRoot}"
cd ./ffc-sfd-data && \
  git pull
cd "${projectRoot}"
cd ./ffc-sfd-permissions && \
  git pull
cd "${projectRoot}"
cd ./ffc-sfd-permissions-api && \
  git pull
cd "${projectRoot}"
cd ./ffc-sfd-ahwp-stub && \
  git pull
cd "${projectRoot}"
cd ./ffc-sfd-proxy && \
  git pull
cd "${projectRoot}"
cd ./ffc-sfd-ingress && \
  git pull
cd "${projectRoot}"
cd ./ffc-sfd-messages && \
  git pull
cd "${projectRoot}"
cd ./ffc-sfd-messages-processor && \
  git pull
cd "${projectRoot}"
cd ./ffc-sfd-customer-receiver-messages && \
  git pull
cd "${projectRoot}"
cd ./ffc-sfd-customer-receiver-payments && \
  git pull
cd "${projectRoot}"
cd ./ffc-sfd-customer-receiver-preferences && \
  git pull
cd "${projectRoot}"
cd ./ffc-sfd-customer-receiver-queries && \
  git pull