#!/usr/bin/bash

totalCpu=0
totalMemory=0
totalPods=0

arr=(
  "ffc-sfd-landing-page"
  "ffc-sfd-auth"
  "ffc-sfd-business"
  "ffc-sfd-data"
  "ffc-sfd-permissions"
  "ffc-sfd-permissions-api"
  "ffc-sfd-ahwp-stub"
  "ffc-sfd-queries"
  "ffc-sfd-messages"
  "ffc-sfd-messages-processor"
  "ffc-sfd-customer-receiver-messages"
  "ffc-sfd-customer-receiver-payments"
  "ffc-sfd-customer-receiver-preferences"
  "ffc-sfd-customer-receiver-queries"
  )

for i in "${arr[@]}"
do
  echo "Getting values from $i"
  valuesFile="https://raw.githubusercontent.com/DEFRA/$i/main/helm/$i/values.yaml"
  maxReplicas=$(curl --silent $valuesFile | yq -r '.deployment.maxReplicas')
  # if maxReplicas does not exist get replicas instead
  if [ "$maxReplicas" = "null" ]; then
    maxReplicas=$(curl --silent $valuesFile | yq -r '.deployment.replicas')
  fi
  # if replicas does not exist set to 1
  if [ "$maxReplicas" = "null" ]; then
    maxReplicas=1
  fi
  cpu=$(curl --silent $valuesFile | yq -e '.container.limitCpu' - | sed -E 's/[A-Za-z]//g')
  memory=$(curl --silent $valuesFile | yq -e '.container.limitMemory' - | sed -E 's/[A-Za-z]//g')
  totalCpu=$(($totalCpu + $cpu * $maxReplicas))
  totalMemory=$(($totalMemory + $memory * $maxReplicas))
  totalPods=$(($totalPods + $maxReplicas))
done

echo "CPU required: $totalCpu"
echo "Memory required: $totalMemory"
echo "Pods required: $totalPods"
